spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  devtools:
    restart:
      enabled: false
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8

demo:
  host: smtp.gmail.com
  port: 587
  clientId: 789011210098-binf1rmg40imskamuulgs7ske03v0pns.apps.googleusercontent.com
  #redirectURL: http://ec2-18-191-69-198.us-east-2.compute.amazonaws.com:8888/Callback
  redirectURL: http://localhost:8888/Callback
  credentialFilePath: react-portfolio-235407-4da656373f73.json #react-portfolio-235407-a23cb1ccec7b.p12
  dataDirectoryPath: datastore
  adminAddress: wdjty326@gmail.com
  apiKey: AIzaSyBSjBuDAZAKN0926aM3-RqkyU705tpNrSM
  gitRepositoriesLink: https://github.com/wdjty326?tab=repositories
  githubLink: https://github.com/
  