spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
security:
  oauth2:
    client:
      client-id: 789011210098-q43oiqggdv61qq7n1m4ur618httu32nn.apps.googleusercontent.com
      client-secret: GIDvu2IZmlkRslQKkHYOMgK1

  