spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
mail:
  credentialFilePath: client_secret.json
  dataDirectoryPath: datastore
  adminAddress: wdjty326@gmail.com
  apiKey: AIzaSyBSjBuDAZAKN0926aM3-RqkyU705tpNrSM
  