spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  devtools:
    restart:
      enabled: false
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8

demo:
  credentialFilePath: client_secret.json
  dataDirectoryPath: datastore
  adminAddress: wdjty326@gmail.com
  apiKey: AIzaSyBSjBuDAZAKN0926aM3-RqkyU705tpNrSM
  gitRepositoriesLink: https://github.com/wdjty326?tab=repositories
  githubLink: https://github.com/
  